"""Add user_id to campaigns

Revision ID: 061c18855fea
Revises: aca8a2bd4d05
Create Date: 2025-10-11 21:34:45.012319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061c18855fea'
down_revision: Union[str, Sequence[str], None] = 'aca8a2bd4d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_campaigns_user_id_users'), 'campaigns', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_email_logs_smtp_id'), table_name='email_logs')
    op.drop_constraint(op.f('fk_email_logs_smtp_id_smtp_accounts'), 'email_logs', type_='foreignkey')
    op.drop_column('email_logs', 'smtp_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_logs', sa.Column('smtp_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_email_logs_smtp_id_smtp_accounts'), 'email_logs', 'smtp_accounts', ['smtp_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_email_logs_smtp_id'), 'email_logs', ['smtp_id'], unique=False)
    op.drop_constraint(op.f('fk_campaigns_user_id_users'), 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'user_id')
    # ### end Alembic commands ###
