"""init models

Revision ID: 142e5b10e08e
Revises: 
Create Date: 2025-10-10 04:21:24.740403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142e5b10e08e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_campaigns_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    op.create_table('recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recipients_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipients'))
    )
    op.create_index(op.f('ix_recipients_email'), 'recipients', ['email'], unique=False)
    op.create_index(op.f('ix_recipients_id'), 'recipients', ['id'], unique=False)
    op.create_index(op.f('ix_recipients_user_id'), 'recipients', ['user_id'], unique=False)
    op.create_table('seedboxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=320), nullable=False),
    sa.Column('last_status', sa.String(length=255), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_seedboxes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seedboxes'))
    )
    op.create_index(op.f('ix_seedboxes_email_address'), 'seedboxes', ['email_address'], unique=False)
    op.create_index(op.f('ix_seedboxes_id'), 'seedboxes', ['id'], unique=False)
    op.create_index(op.f('ix_seedboxes_user_id'), 'seedboxes', ['user_id'], unique=False)
    op.create_table('smtp_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('encrypted_password', sa.String(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('hourly_limit', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('used_today', sa.Integer(), nullable=False),
    sa.Column('last_reset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_smtp_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_smtp_accounts'))
    )
    op.create_index(op.f('ix_smtp_accounts_id'), 'smtp_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_smtp_accounts_user_id'), 'smtp_accounts', ['user_id'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('smtp_id', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('seedbox_status', sa.String(length=100), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_batches_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['smtp_id'], ['smtp_accounts.id'], name=op.f('fk_batches_smtp_id_smtp_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches'))
    )
    op.create_index(op.f('ix_batches_campaign_id'), 'batches', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_batches_id'), 'batches', ['id'], unique=False)
    op.create_index(op.f('ix_batches_smtp_id'), 'batches', ['smtp_id'], unique=False)
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('smtp_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_email_logs_batch_id_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_email_logs_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], name=op.f('fk_email_logs_recipient_id_recipients'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['smtp_id'], ['smtp_accounts.id'], name=op.f('fk_email_logs_smtp_id_smtp_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_logs'))
    )
    op.create_index(op.f('ix_email_logs_batch_id'), 'email_logs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_email_logs_campaign_id'), 'email_logs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_index(op.f('ix_email_logs_recipient_id'), 'email_logs', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_email_logs_smtp_id'), 'email_logs', ['smtp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_logs_smtp_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_recipient_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_campaign_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_batch_id'), table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_index(op.f('ix_batches_smtp_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_campaign_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_smtp_accounts_user_id'), table_name='smtp_accounts')
    op.drop_index(op.f('ix_smtp_accounts_id'), table_name='smtp_accounts')
    op.drop_table('smtp_accounts')
    op.drop_index(op.f('ix_seedboxes_user_id'), table_name='seedboxes')
    op.drop_index(op.f('ix_seedboxes_id'), table_name='seedboxes')
    op.drop_index(op.f('ix_seedboxes_email_address'), table_name='seedboxes')
    op.drop_table('seedboxes')
    op.drop_index(op.f('ix_recipients_user_id'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_id'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_email'), table_name='recipients')
    op.drop_table('recipients')
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
