"""add inbox/spam folder fields to seedbox

Revision ID: 2108834c7d11
Revises: 2a315d74ee85
Create Date: 2025-10-11 14:07:13.849720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2108834c7d11'
down_revision: Union[str, Sequence[str], None] = '2a315d74ee85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seedboxes', sa.Column('imap_inbox_folder', sa.String(length=255), nullable=True))
    op.add_column('seedboxes', sa.Column('imap_spam_folder', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seedboxes', 'imap_spam_folder')
    op.drop_column('seedboxes', 'imap_inbox_folder')
    # ### end Alembic commands ###
