"""Add IMAP fields to seedboxes

Revision ID: 2a315d74ee85
Revises: ce5f4fe4862d
Create Date: 2025-10-11 13:11:24.464218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a315d74ee85'
down_revision: Union[str, Sequence[str], None] = 'ce5f4fe4862d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seedboxes', sa.Column('imap_host', sa.String(length=255), nullable=True))
    op.add_column('seedboxes', sa.Column('imap_port', sa.Integer(), nullable=True))
    op.add_column('seedboxes', sa.Column('imap_username', sa.String(length=320), nullable=True))
    op.add_column('seedboxes', sa.Column('imap_encrypted_password', sa.String(length=255), nullable=True))
    op.add_column('seedboxes', sa.Column('imap_use_ssl', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seedboxes', 'imap_use_ssl')
    op.drop_column('seedboxes', 'imap_encrypted_password')
    op.drop_column('seedboxes', 'imap_username')
    op.drop_column('seedboxes', 'imap_port')
    op.drop_column('seedboxes', 'imap_host')
    # ### end Alembic commands ###
