"""add recipients_count and created_at to campaign_batches

Revision ID: dfe3e349c6fe
Revises: a5fc6488ce19
Create Date: 2025-10-12 02:03:46.921405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfe3e349c6fe'
down_revision: Union[str, Sequence[str], None] = 'a5fc6488ce19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batches_id'), table_name='batches')
    op.drop_table('batches')
    op.add_column('campaign_batches', sa.Column('recipients_count', sa.Integer(), nullable=True))
    op.add_column('campaign_batches', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('campaign_batches', sa.Column('paused', sa.Boolean(), nullable=True))
    op.alter_column('campaign_batches', 'seedbox_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('campaign_batches', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.drop_column('campaign_batches', 'total')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_batches', sa.Column('total', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.alter_column('campaign_batches', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('campaign_batches', 'seedbox_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('campaign_batches', 'paused')
    op.drop_column('campaign_batches', 'created_at')
    op.drop_column('campaign_batches', 'recipients_count')
    op.create_table('batches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batch_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seedbox_status', postgresql.ENUM('unknown', 'inbox', 'spam', 'error', name='seedboxstatus'), autoincrement=False, nullable=True),
    sa.Column('sent_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paused', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('smtp_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipients_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_batches_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['smtp_account_id'], ['smtp_accounts.id'], name=op.f('fk_batches_smtp_account_id_smtp_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches'))
    )
    op.create_index(op.f('ix_batches_id'), 'batches', ['id'], unique=False)
    # ### end Alembic commands ###
